### PR TITLE
fix: Missing property on Select component

### PR DESCRIPTION
**Pull request by ljmotta**
This PR fixes the https://github.com/aerogear/uniforms-patternfly/issues/55 issue by adding a missing property on the `Select` component and updating some dependecies using the https://github.com/aerogear/uniforms-patternfly/pull/46 as reference.

### CODE REVIEW

**Comment by ljmotta** [comment]
Hi @wtrocki @kingsleyzissou , could one of you please review this PR? 

If something is missing or wrong, let me know. :grin:

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
@ljmotta I have merged your PR but then I see that all tests on master started failing:
https://app.circleci.com/pipelines/github/aerogear/uniforms-patternfly/209/workflows/c3a826d7-3c02-43a1-8783-05d01b21f3d4/jobs/204

**Comment by ljmotta** [comment]
@wtrocki As far I could see on the logs, the `@patternfly/react-styles` is missing or it was downloaded the incorrect version, and it's a direct dependency of `@patternfly/react-core`. My guess is because it's missing the `yarn.lock` file on the repo.

I'm not used to the circle-ci, should I open a new PR with just the yarn.lock? or it has an another way to use it?

**Comment by wtrocki** [comment]
@ljmotta Looking at this now

**Pull request merged**
