### PR TITLE
Autofield (Fixes #74)

### LINKED ISSUE #74: AutoField is not using the createAutoField as suggested by uniforms docs
Please see this discussion on uniforms github repo: https://github.com/vazco/uniforms/discussions/941#discussioncomment-679631

They suggest defining `AutoField` using `createAutoField` as in https://github.com/vazco/uniforms/blob/7f1fddbf9dea9572835536d321fe4098de60e355/packages/uniforms-unstyled/src/AutoField.tsx#L15

### PR DESCRIPTION
**Pull request by kingsleyzissou**
- Updated the Autofield to use the `createAutoField` function
- Updated the `uniforms` dependency to `3.4.0`
- Fixed some build issues with the upgrade
- Bumped the versions for `uniforms` & `uniforms-patternfly` in the example app for validation

### CODE REVIEW

**Comment by wtrocki** [comment]
#74

**Comment by wtrocki** [comment]
Amazing. I think we can have it as breaking change as both uniforms were updated. From example point of view user's need to bump their versions. 

Do you mind releasing it with release notes

**Comment by wtrocki** [comment]
@kingsleyzissou I have noticed that docs are outdated (readme should point to latest uniforms

**Comment by kingsleyzissou** [comment]
@wtrocki cool, I'll update the readme and do a new release

**Pull request merged**
